name: ConfigLib
version: 4.6.1
website: https://github.com/Exlll/ConfigLib
description: A library for working with YAML configurations.
author: Exlll
main: de.exlll.configlib.ConfigLib
api-version: 1.19
