name: test-on-pr-or-dev-push

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    branches: [ dev ]
    paths-ignore:
      - '**/README.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK and Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Gradle
        run: ./gradlew test

      - name: Archive test reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/**/*